name: cloud_run_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  firebase_admin: ^0.3.0+1
  google_generative_ai: ^0.4.6
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.3.0
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
